name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install-boost
      run: sudo apt-get install -y libboost-all-dev
    - name: install-cxxtest
      run: sudo apt-get install -y cxxtest
    - name: install-ctags
      run: sudo apt-get install -y ctags
    - name: submodules
      run: git submodule update --init
    - name: cmake
      run: mkdir -p c++/Release && cd c++/Release && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      run: cd c++/Release && make
    - name: test
      run: cd c++/Release && make test
